version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:

services:
  db:
    image: postgres:13
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: foodgram_backend:latest
    env_file: .env
    restart: always
    volumes:
      - data_value:/code/data/
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db

  frontend:
    image: foodgram_frontend:latest
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    env_file: .env
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
